### ISSUE TITLE
Update lint to ignore docstring requirements for class properties

### ISSUE THREAD

**Issue by SebDuff** [FootyStats/footy#19]
I don't think there is much value in requiring docstrings for standard properties unless they have enriched functionality. They are essentially just getting/setting the encapsulated data. Happy to add docstrings if it will make the overall docs easier to read though, what do you think? e.g.
```
    @property
    def points(self):
        return self._points

    @points.setter
    def points(self, points):
        self._points = points
```
Example class with docstring on properties: https://github.com/FootyStats/footy/blob/feature/data_model_team/footy/domain/Team.py

**Comment by dallinb** [comment]
I think they should still be documented.  If only to clarify the data types of the parameters of the setter or the return type of the property (in this example both being an int).  While there is definitely a case for having them separated if the setter is doing a large amount of extra processing, but in this basic example, would it not be easier (and more [Pythonesque](https://en.wiktionary.org/wiki/Pythonesque)) to just have:

```Python
        def points(self, points=None):
        """
        Get or set the number of points for the Team object.

        Parameters
        ----------
        points : int
            The number of points to set for the Team object.

        Returns
        -------
        int
            The number of points held by the Team object.
        """
        if points is not None:
            self._points = points
        return self._points
```

**Comment by SebDuff** [comment]
I agree, that sounds pragmatic
